services:
    tap-dashboard:
        build: .
        container_name: tap_dashboard
        ipc: host
        ports:
            - '5000:5000'
        restart: always
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DB_NAME: scraper_db
            DB_USERNAME: tapuser
            DB_PASSWORD:
            ADMIN_PASSWORD:
        depends_on:
            - db
    db:
        image: postgres:15
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_DB: scraper_db
            POSTGRES_USER: tapuser
            POSTGRES_PASSWORD:
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5433:5432'

volumes:
    postgres_data:
